#!/bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

PID=`pidof -o %PPID /usr/sbin/mfsmaster`
case "$1" in
  start)
    stat_busy "Starting MooseFS Master Daemon"
    if [ -z "$PID" ]; then 
       /usr/sbin/mfsmaster
    fi
    if [ ! -z "$PID" -o $? -gt 0 ]; then
      stat_fail
    else
      PID=`pidof -o %PPID /usr/sbin/mfsmaster`
      echo $PID > /var/run/mfsmaster.pid
      add_daemon mfsmaster
      stat_done
    fi
    ;;
  stop)
    stat_busy "Stopping MooseFS Master Daemon"
    [ ! -z "$PID" ]  && kill $PID &> /dev/null
    if [ $? -gt 0 ]; then
      stat_fail
    else
      rm_daemon mfsmaster
      stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"  
esac
